- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleTimeAgent
  name: CCD Agent Role
  components:
  - type: MindRole
    antagPrototype: TimeAgent
    exclusiveAntag: true
    roleType: SoloAntagonist
  - type: TimeAgentRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleConspiracy
  name: Conspirator Role
  components:
  - type: Mindrole
    antag prototype: Conspirator
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: ConspiratorRole
