- type: cargoProduct
  id: LoyaltyImplants
  icon:
    sprite: Objects/Specific/Medical/implanter.rsi
    state: implanter0
  product: CrateSecurityLoyaltyImplants
  cost: 4000
  category: cargoproduct-category-name-security
  group: market
